### ISSUE TITLE
Modify how `in` and `out` options are used in this module

### ISSUE THREAD

**Issue by iamvdo** [iamvdo/pleeease#42]
Same as #41.

* in `pleeease-cli`, `in` and `out` should work as they do for now
* in `pleeease`, `in` and `out` should not be defined by default. Thus, if defined in `opts`, they can be used for sourcemaps generation.

**Comment by designorant** [comment]
Yes pleeease! This is actually why my sourcemaps are inlined. Otherwise they just get referenced as `app.min.map`. Bear in mind I've got a few files and use [grunt-pleeease](https://github.com/danielhusar/grunt-pleeease) which [has its own problems](https://github.com/danielhusar/grunt-pleeease/issues/6).

**Comment by iamvdo** [comment]
Absolutely, there are bugs right now generating sourcemaps, because of that.
It's at the top of my todo list. ;)

**Comment by designorant** [comment]
Thanks @iamvdo!

**Comment by iamvdo** [comment]
Fixed 603aa2c
